### ISSUE TITLE
UVR-DeEcho-DeReverb not really working (Amazon Linux)

### ISSUE THREAD

**Issue by venkat-sf** [nomadkaraoke/python-audio-separator#45]
I am trying to use the _UVR-DeEcho-DeReverb_ Model and it's not really working -- producing no audio or some kind of garbled audio. The command options I am using can be seen below. With MDX-Net Model like _Reverb_HQ_By_FoxJoy_, things seem to work fine. Am I missing something?

`audio-separator --single_stem=instrumental --output_format=wav --output_dir=output/UVR-DeEcho-DeReverb/ --model_file_dir=models/ --model_filename=UVR-DeEcho-DeReverb.pth --vr_window_size=256 --vr_aggression=5 [input_file]`

**Comment by venkat-sf** [comment]
Was able to get decent output on about 50% of the inputs I tried with, by tweaking the parameters (see below).

`--vr_window_size=320 --vr_aggression=1 --vr_enable_tta`

**Comment by beveradb** [comment]
Thanks for experimenting with it! To be honest I haven't gotten around to testing that specific model personally yet so it may be that in UVR it just gets a different set of default parameters - or I may have just messed up somehow 😅 

I'll try and give it a try myself, but if you're able to provide a test audio file and compare the output from UVR vs. the output from audio-separator that would be really helpful for me to do a better test!

**Comment by venkat-sf** [comment]
Thank you, @beveradb! Will try to get you a test file that I can share publicly.

**Comment by venkat-sf** [comment]
Here's a [Zip file](https://github.com/karaokenerds/python-audio-separator/files/14530562/VR-BlankOutput-Clips.zip) containing a few clips that produce blank output

**Comment by beveradb** [comment]
Hey @venkat-sf, I know it's been *checks notes* 7 months since you raised this issue, but I wanted to let you know this is finally fixed and the `UVR-DeEcho-DeReverb.pth` model definitely works in the latest version of `audio-separator`, version `0.19.3` onwards! 🎉 

For example, here is the output from one of your test tracks [00036_0009_non-sf_split_Jazz-Hall.wav](https://www.dropbox.com/scl/fi/q6uum5mxsdy01c84eamfp/00036_0009_non-sf_split_Jazz-Hall.wav?rlkey=bczyra6drhbiuznkvxjl4j11u&dl=0):

`audio-separator -d -m UVR-DeEcho-DeReverb.pth tracks/DeEcho-DeReverb-Test-Tracks/00036_0009_non-sf_split_Jazz-Hall.wav`

- [00036_0009_non-sf_split_Jazz-Hall_(Reverb)_UVR-DeEcho-DeReverb.flac](https://www.dropbox.com/scl/fi/uptfiww4xr50mjstywdy1/00036_0009_non-sf_split_Jazz-Hall_-Reverb-_UVR-DeEcho-DeReverb.flac?rlkey=2a1lja4bt27yfwewl40iodaby&dl=0)
- [00036_0009_non-sf_split_Jazz-Hall_(No Reverb)_UVR-DeEcho-DeReverb.flac](https://www.dropbox.com/scl/fi/dflquryjk5pfokr51hmuk/00036_0009_non-sf_split_Jazz-Hall_-No-Reverb-_UVR-DeEcho-DeReverb.flac?rlkey=7s2ozbiz5x3sbyoifwzpl8u2a&dl=0)

Hope this helps! I'm closing this issue now as I believe it's resolved 😄
