### ISSUE TITLE
The processing results of the UVR-DeNoise. pth model are different from those of UVR5 client.

### ISSUE THREAD

**Issue by zhyqieqie** [nomadkaraoke/python-audio-separator#79]
try:https://noisereducer.media.io/audio-2022/index-page/denoise-before.wav

What does the generated file  (Instrumental) _UVR DeNoise. wav represent?
Should noise.wav and exclue_noise.wav be better?

**Comment by beveradb** [comment]
Sorry, I'm not exactly sure which stem is supposed to be which - I haven't had much luck with the denoise model, I suspect it needs further implementation work to get it working correctly in `audio-separator`

PRs very welcome, or let me know if you want to pair program on it some time!

**Comment by beveradb** [comment]
So I finally got around to testing this today. 
You're right, the output **_filename_** from the DeNoise model is confusing because it says "Instrumental" rather than "No Noise", but I don't think the results are any different.

See below:

Results from processing your [test file ](https://noisereducer.media.io/audio-2022/index-page/denoise-before.wav) with UVR, with the below settings:

<img width="792" alt="image" src="https://github.com/user-attachments/assets/a7c3c177-582d-4a5d-baba-5a8f6a81c614">

- [1_denoise-before_UVR-DeNoise_(Noise).flac](https://www.dropbox.com/scl/fi/wajmcoen08j6md20f058p/1_denoise-before_UVR-DeNoise_-Noise.flac?rlkey=yaxwujwutt6i5bw4o36wanppe&dl=0)
- [1_denoise-before_UVR-DeNoise_(No Noise).flac](https://www.dropbox.com/scl/fi/30sxmda14d9w611l1di94/1_denoise-before_UVR-DeNoise_-No-Noise.flac?rlkey=e8re3x4u5fss5z7le54jnvsog&dl=0)

Results from processing the same file with `audio-separator -d -m UVR-DeNoise.pth ~/Downloads/denoise-before.wav`

- [denoise-before_(Noise)_UVR-DeNoise.flac](https://www.dropbox.com/scl/fi/vs7fggmldhb5xz12uxnn7/denoise-before_-Noise-_UVR-DeNoise.flac?rlkey=nldromhnz9p8j0s2u7ie19fki&dl=0)
- [denoise-before_(Instrumental)_UVR-DeNoise.flac](https://www.dropbox.com/scl/fi/apowo9l2rs5ajnlu217h3/denoise-before_-Instrumental-_UVR-DeNoise.flac?rlkey=ioslx559dvnhyd7vdz95m41pz&dl=0)

To my ears, those results seem pretty much identical.

So, the only bug is the output filename saying "Instrumental" instead of "No Noise" which is fair, I'll see if I can fix that in the next release!

**Comment by beveradb** [comment]
Fixed in commit https://github.com/nomadkaraoke/python-audio-separator/commit/4cd059e4b1a974ed96617e19d3a4b9b78efa4e2f

The secondary stem output filename should now be named correctly, in `audio-separator` version `0.19.3` and newer 🎉
